# Shopify Theme Configuration
# Use environment variables for sensitive data

development:
  password: ${SHOPIFY_PASSWORD}
  theme_id: ${SHOPIFY_THEME_ID}
  store: ${SHOPIFY_STORE_URL}
  timeout: 60s
  ignore_files:
    - '*.git/*'
    - '*.DS_Store'
    - '*.env'
    - 'node_modules/*'

staging:
  password: ${SHOPIFY_STAGING_PASSWORD}
  theme_id: ${SHOPIFY_STAGING_THEME_ID}
  store: ${SHOPIFY_STORE_URL}
  timeout: 60s
  ignore_files:
    - '*.git/*'
    - '*.DS_Store'
    - '*.env'
    - 'node_modules/*'

production:
  password: ${SHOPIFY_PRODUCTION_PASSWORD}
  theme_id: ${SHOPIFY_PRODUCTION_THEME_ID}
  store: ${SHOPIFY_STORE_URL}
  timeout: 60s
  ignore_files:
    - '*.git/*'
    - '*.DS_Store'
    - '*.env'
    - 'node_modules/*'
